### ISSUE TITLE
[ios] Podspec not found error

### ISSUE THREAD

**Issue by MrLightful** [arrrrny/zikzak_inappwebview#1]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.24.3        |
| Plugin version        |      1.0.0         |
| Android version       |               |
| iOS version           |        iOS 18       |
| macOS version         |               |
| Xcode version         |        16       |
| Google Chrome version |               |

Device information: iOS Simulator

## Description

[!] No podspec found for `zikzak_inappwebview_ios` in `.symlinks/plugins/zikzak_inappwebview_ios/ios`

**Comment by shilpanavale** [comment]
Me also getting same error....Please solve it.

[!] No podspec found for `zikzak_inappwebview_ios` in `.symlinks/plugins/zikzak_inappwebview_ios/ios`

**Comment by MrLightful** [comment]
> Please solve it.

If super urgent, you can use my fork from the pull request.

```
dependency_overrides:

  zikzak_inappwebview_ios:
    git:
      url: https://github.com/MrLightful/zikzak_inappwebview.git
      path: zikzak_inappwebview_ios
      ref: 639de5f7ff41d13647109ed4600d4c4f7746b830
```

But I'm pretty sure, @arrrrny will merge it/fix it within a few hours.
